### ISSUE TITLE
Failing to upload a file should exit the process with exit code 1

### ISSUE THREAD

**Issue by romanschejbal** [SamKirkland/FTP-Deploy-Action#123]
**Bug Description**
Currently, failing to upload a file silently fails and the action pretends to be successful.

**Expected Behaviour**
The action should exit with exit code 1 i.e. failed

**My Action Config**
Irrelevant

**Comment by SamKirkland** [comment]
Thanks Roman.

This is not as intended, I'll take a look.

What specific error did you get? This appears to be setting a failed response correctly (at least for auth errors).

![image](https://user-images.githubusercontent.com/7682814/99285920-c88fab80-27fd-11eb-9b68-d85221dc2c6a.png)

**Comment by romanschejbal** [comment]
Hey @SamKirkland thanks for the quick reply, [here](https://www.dropbox.com/s/122kp39q03ukah3/Screenshot%202020-11-17%20at%2000.19.52.png?dl=0)'s a more detailed screenshot

**Comment by Raphael-Stellwag** [comment]
I have a similiar error, when the remote server suddenly closses the connection:

```
 ----------------------------------------------------------------
Making changes to 130 files to sync server state
Uploading: 6.65 MB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
creating folder "assets/"
Error: Client is closed
    at /home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3704:29
    at new Promise (<anonymous>)
    at FTPContext.handle (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3684:16)
    at Client.sendIgnoringError (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:2745:25)
    at Client._openDir (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3251:20)
    at Client.ensureDir (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3242:24)
    at /home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:1962:121
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:1823:71
    at new Promise (<anonymous>)
Closing reason: Error: read ECONNRESET (data socket)
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {
  code: 'ECONNRESET'
}
Error: Client is closed
    at /home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3704:29
    at new Promise (<anonymous>)
    at FTPContext.handle (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3684:16)
    at Client.sendIgnoringError (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:2745:25)
    at Client._openDir (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3251:20)
    at Client.ensureDir (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3242:24)
    at /home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:1962:121
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:1823:71
    at new Promise (<anonymous>)
Closing reason: Error: read ECONNRESET (data socket)
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {
  code: 'ECONNRESET'
}
----------------------------------------------------------------
Time spent hashing:               71 milliseconds
Time spent connecting to server:  1.1 seconds
Time spent deploying:             3 milliseconds (2.25 GB/second)
  - changing dirs:                90 milliseconds
  - logging:                      270 milliseconds
----------------------------------------------------------------
Total time:                       1.7 seconds
----------------------------------------------------------------
```

After this the job continues, which is not the inteded behaviour I think

**Comment by davetapley** [comment]
I'm seeing same `Error: Client is closed` as @Raphael-Stellwag ⬆️, but:

@SamKirkland I see on https://github.com/SamKirkland/FTP-Deploy-Action/issues/144#issuecomment-742969962 you speculate there are two issues going on here. So I'll leave this issue for "should exit non-zero" and I've opened #153 for the underlying issue, hope that's 👌🏻 😁
