### ISSUE TITLE
Example for self signed certs

### ISSUE THREAD

**Issue by mfsbo** [SamKirkland/FTP-Deploy-Action#147]
I have run an action on a FTP server where the certificate is self-signed.
The result was 
```
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
Error: Error: self signed certificate
```
My assumption from documentation was that security is set to loose by default so it should not worry about the certificate list. However, I am not sure what option should I use to accept self signed certificate.

It would be good to have an example where self signed certificate can be used to connect to ftp.

**Comment by mfsbo** [comment]
Closing it as duplicate of #127
