### ISSUE TITLE
Action validates certificate even when `security` is set to `loose`

### ISSUE THREAD

**Issue by Yanisky** [SamKirkland/FTP-Deploy-Action#149]
**Bug Description**
Maybe it's not a bug but a misunderstanding from my part. I'm trying to connect through FTPS but my cpanel provider has a generic certificate that doesn't match the domain name and the action is failing with:

```Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: ***. is not in the cert's altnames:```

I thought that by setting `security` to `loose` it wouldn't do certificate validation.

**My Action Config**
```yaml
- name: public_html deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: ./public_html/
        server-dir: ./public_html/
        security: loose
        dry-run: true
```

**My Action Log**
```
  Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: ***. is not in the cert's altnames: DNS:*.cleaned.com, DNS:cleaned.com
    at Object.checkServerIdentity (tls.js:279:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1331:27)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  reason: "Host: ***. is not in the cert's altnames: DNS:*.cleaned.com, DNS:cleaned.com",
  host: '***',
  cert: {
    subject: [Object: null prototype] { CN: '*.cleaned.com' },
    issuer: [Object: null prototype] {
      C: 'GB',
      ST: 'Greater Manchester',
      L: 'Salford',
      O: 'Sectigo Limited',
      CN: 'Sectigo RSA Domain Validation Secure Server CA'
    },
    subjectaltname: 'DNS:*.cleaned.com, DNS:cleaned.com',
    infoAccess: [Object: null prototype] {
      'CA Issuers - URI': [Array],
      'OCSP - URI': [Array]
    },
    modulus: 'DA00CA3FEBFA6C07D0B20C956941394EAE287BF1700F80C6635B1BE539BC7AE12631D0EAECFC33B6A59FE950626230BE51E8BB8C1FC9E380ADE4A37A23E444EACA7EFE234CA60E938EFA0BD92F307C4AB774BD44C49402B43260050AE2F6216D867AB1DEE578FAA0AF5237EB2DC1C04F813BDE449E26B31B637BE0B3687EACB4B2F7D846A736FF9E9D3987D2FF351F81E3FFB7701B0DB24EE3C7ED94A0364E48AA2857C2CAF7DEC0E1003A4658051CECC5382F431EF0A1D0C479D86C02830A91DFD619E9334419074F1FD4B9A50366C9D7A7020BD883965B75010F44FA07C5D3692A420AA447B5518DB7E143DBB78B194FF770FBA2ABD740C99C4E07D3A1A4D7',
    bits: 2048,
    exponent: '0x10001',
    pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 da 00 ca 3f eb fa 6c 07 d0 b2 0c 95 69 41 39 4e ae ... 244 more bytes>,
    valid_from: 'Nov  2 00:00:00 2020 GMT',
    valid_to: 'Nov  3 23:59:59 2021 GMT',
    fingerprint: '15:FC:15:9B:31:0A:A1:A1:4C:28:BA:A3:84:07:29:AA:BE:51:BA:5A',
    fingerprint256: '6E:23:D0:2A:89:17:57:55:ED:66:C4:98:5B:82:47:6B:EA:EC:B6:E0:43:49:DF:95:01:1F:F6:E5:51:1E:B6:33',
    ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
    serialNumber: '0622ECFB2C9E40CB65FC818024807148',
    raw: <Buffer 30 82 05 b8 30 82 04 a0 a0 03 02 01 02 02 10 06 22 ec fb 2c 9e 40 cb 65 fc 81 80 24 80 71 48 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 81 8f 31 ... 1418 more bytes>,
    issuerCertificate: {
      subject: [Object: null prototype],
      issuer: [Object: null prototype],
      infoAccess: [Object: null prototype],
      modulus: 'D67333D6D73C20D000D21745B8D63E07A23FC741EE3230C9B06CFDF49FCB12980F2D3F8D4D010C820F177F622EE9B84879FB16834EADD7322593B707BFB9503FA94CC3402AE939FFD981CA1F163241DA8026B9237A87201EE3FF209A3C95446F8775069040B4329316091008233ED2DD870F6F5D51146A0A69C54F017269CFD3934C6D04A0A31B827EB19AB9EDC59EC537789F9A0834FB562E58C4090E06645BBC37DCF19F2868A856B092A35C9FBB8898081B241DAB3085AEAFB02E9E7A9DC1C0421CE202F0EAE04AD2EF900EB4C14016F06F85424A64F7A430A0FEBF2EA3275A8E8B58B8ADC319178463ED6F56FD83CB6034C474BEE69DDBE1E4E5CA0C5F15',
      bits: 2048,
      exponent: '0x10001',
      pubkey: <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 d6 73 33 d6 d7 3c 20 d0 00 d2 17 45 b8 d6 3e 07 a2 ... 244 more bytes>,
      valid_from: 'Nov  2 00:00:00 2018 GMT',
      valid_to: 'Dec 31 23:59:59 2030 GMT',
      fingerprint: '33:E4:E8:08:07:20:4C:2B:61:82:A3:A1:4B:59:1A:CD:25:B5:F0:DB',
      fingerprint256: '7F:A4:FF:68:EC:04:A9:9D:75:28:D5:08:5F:94:90:7F:4D:1D:D1:C5:38:1B:AC:DC:83:2E:D5:C9:60:21:46:76',
      ext_key_usage: [Array],
      serialNumber: '7D5B5126B476BA11DB74160BBC530DA7',
      raw: <Buffer 30 82 06 13 30 82 03 fb a0 03 02 01 02 02 10 7d 5b 51 26 b4 76 ba 11 db 74 16 0b bc 53 0d a7 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0c 05 00 30 81 88 31 ... 1509 more bytes>,
      issuerCertificate: [Object]
    }
  },
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}
```

**Comment by retiutut** [comment]
I think the following code may be reversed:

https://github.com/SamKirkland/FTP-Deploy-Action/blob/1cffb780cfa41bfdec1b7567ce51b2faf919f9c1/dist/index.js#L2072

To test:
- had the same issue using FTPS
- did not specify security at first
- added security `strict` option
- Success!

**Comment by Mixermachine** [comment]
> I think the following code may be reversed:
> 
> https://github.com/SamKirkland/FTP-Deploy-Action/blob/1cffb780cfa41bfdec1b7567ce51b2faf919f9c1/dist/index.js#L2072
> 
> To test:
> 
> * had the same issue using FTPS
> * did not specify security at first
> * added security `strict` option
> * Success!
> 
> https://stackoverflow.com/a/16311147

I second this. Worked for me.
My provider also does ship a generic SSL cert.

@SamKirkland 
The meaning of strict and loose is inverse.
When I put strict, it accepts the connection even thought the DNS does not match

**Comment by kenlog** [comment]
The meaning of strict and loose is inverse for me too
