### ISSUE TITLE
None of the available transfer strategies work.

### ISSUE THREAD

**Issue by workatease** [SamKirkland/FTP-Deploy-Action#159]
**Bug Description**
FTP deploy fails with the below error and stops.

**My Action Config**
``` - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ****
          username: *****
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          log-level: verbose
```

**My Action Log**

> CDUP
< 250 OK. Current directory is /domains/alpheternity.com/public_html

  completed
uploading "css/bootstrap.css"
Trying to find optimal transfer strategy...
> EPSV
< 229 Extended Passive mode OK (|||35571|)

> PASV
< 227 Entering Passive Mode (5,2,89,15,137,27)

Error: None of the available transfer strategies work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3308:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: None of the available transfer strategies work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3308:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
----------------------------------------------------------------

**Comment by Sheepsody** [comment]
Hi,

I ran into the same issue yesterday (although my log was maybe not as detailed).
I just had to enable the passive mode if my vftps config file, adding the following lines :

``
# /etc/vsftpd.conf
pasv_enable=Yes
pasv_min_port=MIN
pasv_max_port=MAX
``

Does it help in any way ?

**Comment by luan-hubner** [comment]
@Sheepsody It's work fine, I did it, add this lines with the range 10000-11000 and add a output/input firewall rule to TCP between 10000 and 11000. Working perfect now.
