### ISSUE TITLE
Errors with each protocol method

### ISSUE THREAD

**Issue by FlopRe** [SamKirkland/FTP-Deploy-Action#172]
**Bug Description**
I am having an issue with the deploy action timing out. I've changed main.yaml a few times to see if my config is wrong but I highly doubt it is. I can connect just fine using WinSPC. 
One thing to note: my host only supports SFTP over port 22 - do I use the 'protocol' attribute or do I leave it out of the main.yml? I've included error log for protocol: ftp, ftps and ftps-legacy.

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: **
        username: **
        password: ${{ secrets.ftp_password }}
        port: 22
```

**Error when not including 'protocol' (aka leaving it to default 'ftp')**
```
Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3793:58)
    at Object.onceWrapper (events.js:299:28)
    at Socket.emit (events.js:210:5)
    at Socket._onTimeout (net.js:469:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: Error: Timeout (control socket)
```

**Error when using 'protocol: ftps-legacy'**
```
[Error: 140587743995776:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
 (control socket)] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ERR_SSL_WRONG_VERSION_NUMBER'
}
Error: Error: 140587743995776:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

**Error when using 'protocol: ftps'**
```
Error: Server sent FIN packet unexpectedly, closing connection.
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3602:56)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Error: Error: Server sent FIN packet unexpectedly, closing connection.
```

**Comment by SamKirkland** [comment]
A few issues exist in version 4. Support for flakey FTP connections and non-standard FTP implementations is not as good.

If you want you can use version 3 - https://github.com/SamKirkland/FTP-Deploy-Action/tree/3.1.1

**Comment by FlopRe** [comment]
Thank you. I have tried using 3.1.1 and now get the error below instead, I can also see that your SFTP test run is failing - might this be a problem?

```
Uploading files
  /usr/bin/git ftp push --force --auto-init --verbose --syncroot=./public/ --user=*** --passwd=*** --dry-run --insecure sftp://***
  Fri Mar 19 10:37:11 UTC 2021: git-ftp version 1.5.1 running on Linux d75af2b7f84d 5.4.0-1040-azure #42-Ubuntu SMP Fri Feb 5 15:39:06 UTC 2021 x86_64 GNU/Linux
  Fri Mar 19 10:37:11 UTC 2021: Forced mode enabled.
  Fri Mar 19 10:37:11 UTC 2021: Auto init if needed.
  Fri Mar 19 10:37:11 UTC 2021: Using syncroot ./public/ if exists.
  Fri Mar 19 10:37:11 UTC 2021: fatal: Unrecognised option: sftp://***
Error: The process '/usr/bin/git' failed with exit code 3
```

main.yml:
```
on: push
name: 🚀 Deploy website on push
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      
      - name: 📂 Sync GitHub files to FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://***
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          git-ftp-args: --dry-run --insecure
```

**Comment by williansmartins** [comment]
@FlopRe  I had this erros too, only works on 2.0.0 version...
