### ISSUE TITLE
Some files are uploaded and some not

### ISSUE THREAD

**Issue by aatosmedia** [SamKirkland/FTP-Deploy-Action#190]
**Bug Description**
png, jpg and js files are uploaded and directories are created, but html and css files are not uploaded.

**My Action Config**
```yaml
on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: IP address
        username: tommsaks
        password: ${{ secrets.ftp_password_azure }}
        server-dir: /public_html/gittest/
        protocol: ftps
        security: strict
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@4.0.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
No file exists on the server "/public_html/gittest/.ftp-deploy-sync-state.json" - this much be your first publish! 🎉
The first publish will take a while... but once the initial sync is done only differences are published!
If you get this message and its NOT your first publish, something is wrong.
----------------------------------------------------------------
Local Files:	8
Server Files:	8
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
➕ Upload: favicon-esimerkki.jpg
➕ Upload: FormChek.js
📁 Create: images
➕ Upload: images/design-from-Finland.png
➕ Upload: images/index.html
➕ Upload: index.html
➕ Upload: index123.html
➕ Upload: ohjeet.css
----------------------------------------------------------------
Making changes to 8 files to sync server state
Uploading: 218 kB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
creating folder "images/"
uploading "favicon-esimerkki.jpg"
uploading "FormChek.js"
400 level error from server when performing action - retrying...
FTPError: 426 Failure reading network stream.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3759:39)
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3600:44)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 426
}
Connection closed. This library does not currently handle reconnects
FTPError: 426 Failure reading network stream.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3759:39)
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3600:44)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 426
}
FTPError: 426 Failure reading network stream.
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3759:39)
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3600:44)
    at TLSSocket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:286:13)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'FTPError',
  code: 426
}
----------------------------------------------------------------
Time spent hashing:               23 milliseconds
Time spent connecting to server:  903 milliseconds
Time spent deploying:             1.3 seconds (161 kB/second)
  - changing dirs:                470 milliseconds
  - logging:                      135 milliseconds
----------------------------------------------------------------
Total time:                       2.9 seconds
----------------------------------------------------------------
```

**Comment by Macin609** [comment]
I'm facing the same problem. Server firewall turned off, ftp instead ftps, selected dir with only few files, but nothing worked. 😞

**Comment by patrickbussmann** [comment]
I have the same, too.

```
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
➕ Upload: .env
➕ Upload: .env.test
📁 Create: .idea
➕ Upload: .idea/beratung.iml
📁 Create: .idea/codeStyles
➕ Upload: .idea/codeStyles/codeStyleConfig.xml
➕ Upload: .idea/modules.xml
➕ Upload: .idea/php.xml
➕ Upload: .idea/symfony2.xml
➕ Upload: .idea/vcs.xml
📁 Create: assets
📁 Create: assets/fonts
📁 Create: assets/fonts/metropolis
➕ Upload: assets/fonts/metropolis/Metropolis-Black.otf
➕ Upload: assets/fonts/metropolis/Metropolis-BlackItalic.otf
➕ Upload: assets/fonts/metropolis/Metropolis-Bold.otf
➕ Upload: assets/fonts/metropolis/Metropolis-BoldItalic.otf
➕ Upload: assets/fonts/metropolis/Metropolis-ExtraBold.otf
➕ Upload: assets/fonts/metropolis/Metropolis-ExtraBoldItalic.otf
➕ Upload: assets/fonts/metropolis/Metropolis-ExtraLight.otf
➕ Upload: assets/fonts/metropolis/Metropolis-ExtraLightItalic.otf
```

And the folder's are empty.
So the action only creates folders but not uploading files 😢

**Comment by grandeljay** [comment]
I've also run into this problem but css files uploaded fine. I also got stuck at the fonts:
* font.eot (uploaded)
* font.svg (uploaded)
* font.ttf (uploaded)
* font.woff (uploaded)
* **font.woff2 (failed)**


And I get the error:
```log
FTPError: 426 Failure reading network stream.
```

**Comment by marcosdipaolo** [comment]
any solution?

**Comment by natenjo** [comment]
I can confirm this behavour on two different ftps servers.  One with the free hosting provider [lima-city](https://www.lima-city.de/webhosting/webspace-kostenlos) and one with the paid webhosting provider [easyname](https://www.easyname.de/de/hosting/vergleich/id/80)

For both I do not have insight on the server configuration, as these are hosted providers, but maybe you can check e.g. with lima-city, as registration is free.

After switching from ftps to ftp (which was possible on my privider easyname) if worked, but is not a good solution, as it is not encrypted..


I wanted to upload a structure of 52 objects (mainly php, html css files)

Attatched is my log
[github actions log.txt](https://github.com/SamKirkland/FTP-Deploy-Action/files/8307751/github.actions.log.txt)

**Comment by prygunov** [comment]
I have the same problem with vsftpd, protocol ftps

**Comment by mdkhairul773islam** [comment]
I have the same, too.
**My Action Config**
on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.khairulislam.xyz
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/
          protocol: ftp
          port: 21
          dry-run: true
          #ARGS: --verbose

**My action log** 

Run SamKirkland/FTP-Deploy-Action@4.0.0
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
No file exists on the server "/public_html/.ftp-deploy-sync-state.json" - this much be your first publish! 🎉
The first publish will take a while... but once the initial sync is done only differences are published!
If you get this message and its NOT your first publish, something is wrong.
----------------------------------------------------------------
Local Files:	3
Server Files:	3
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
➕ Upload: frank.html
➕ Upload: LICENSE
➕ Upload: README.md
----------------------------------------------------------------
Making changes to 3 files to sync server state
Uploading: [11](https://github.com/mdkhairul773islam/cv-template/actions/runs/3763024924/jobs/6396214644#step:3:12).7 kB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
uploading "frank.html"
uploading "LICENSE"
uploading "README.md"
----------------------------------------------------------------
🎉 Sync complete. Saving current server state to "/public_html/.ftp-deploy-sync-state.json"
----------------------------------------------------------------
Time spent hashing:               15 milliseconds
Time spent connecting to server:  916 milliseconds
Time spent deploying:             1 millisecond ([14](https://github.com/mdkhairul773islam/cv-template/actions/runs/3763024924/jobs/6396214644#step:3:15).9 MB/second)
  - changing dirs:                [18](https://github.com/mdkhairul773islam/cv-template/actions/runs/3763024924/jobs/6396214644#step:3:19)1 milliseconds
  - logging:                      59 milliseconds
----------------------------------------------------------------
Total time:                       4 minutes [21](https://github.com/mdkhairul773islam/cv-template/actions/runs/3763024924/jobs/6396214644#step:3:22).7 seconds
----------------------------------------------------------------
