### ISSUE TITLE
FTPError: 550 The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by adeel-rana** [SamKirkland/FTP-Deploy-Action#302]
I am facing the below error while replacing/overwriting the file.

Making changes to 2 files/folders to sync server state
Uploading: 0 B -- Deleting: 0 B -- Replacing: 604 kB
----------------------------------------------------------------
replacing "CMS.dll"
----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------
----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------
FTPError: 550 The process cannot access the file because it is being used by another process. 
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4774:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4615:44)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:1[88](https://github.com/AzeemArshad/CMS/runs/7373755805?check_suite_focus=true#step:9:89):23) {
  code: 550
}
Error: FTPError: 550 The process cannot access the file because it is being used by another process.

**Comment by Cyrildu31** [comment]
Hello,
I have the same Issue.
Did you found a fix ?
Thank you.
