### ISSUE TITLE
Server sent FIN packet unexpectedly, closing connection.

### ISSUE THREAD

**Issue by HadiNiazi** [SamKirkland/FTP-Deploy-Action#358]
**Bug Description**
I mentioned the bug which is the FIN packet unexpectedly, closing the connection. I am following your latest sftp.yml same as you mentioned, but I don't why this error is happening.

**My Action Config**
```yaml
name: FTPS Test

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.mytp
          username: myuser
          password: mypass
          protocol: ftps
          server-dir: ./public_html/
```

**My Action Log**
```
   Error: Server sent FIN packet unexpectedly, closing connection.
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.0/dist/index.js:4617:56)
    at TLSSocket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Error: Error: Server sent FIN packet unexpectedly, closing connection.
```

**Comment by PseudoNinja** [comment]
Seeing the same issue :

```
Error: Server sent FIN packet unexpectedly, closing connection.
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5097:56)
    at TLSSocket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: Error: Server sent FIN packet unexpectedly, closing connection.
```

**Comment by HadiNiazi** [comment]
closing issue because it's duplicated
