### ISSUE TITLE
FTP Deployment Failed on Push

### ISSUE THREAD

**Issue by shahriarshamit** [SamKirkland/FTP-Deploy-Action#391]
**Bug Description**
FTP deployment to Git push is failing with error => Error: Error: Client is closed because read ECONNRESET (data socket)

**My Action Config**
```yaml
on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_hostname }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: ${{ secrets.ftp_hostpath }}
```

**My Action Log**
```
Run SamKirkland/FTP-Deploy-Action@v4.3.4
  with:
    server: ***
    username: ***
    password: ***
    server-dir: ***
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
No file exists on the server "***.ftp-deploy-sync-state.json" - this must be your first publish! 🎉
The first publish will take a while... but once the initial sync is done only differences are published!
If you get this message and its NOT your first publish, something is wrong.
----------------------------------------------------------------
Local Files:	56
Server Files:	0
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
📁 Create: assets
📁 Create: assets/css
📁 Create: assets/fonts
📁 Create: assets/icons
📁 Create: assets/images
📁 Create: assets/js
📄 Upload: assets/css/bootstrap-theme.css
📄 Upload: assets/css/bootstrap-theme.css.map
📄 Upload: assets/css/bootstrap-theme.min.css
📄 Upload: assets/css/bootstrap.css
📄 Upload: assets/css/bootstrap.css.map
📄 Upload: assets/css/bootstrap.min.css
📄 Upload: assets/css/font-awesome.css
📄 Upload: assets/css/font-awesome.min.css
📄 Upload: assets/css/jquery-ui.css
📄 Upload: assets/css/jquery-ui.min.css
📄 Upload: assets/css/jquery-ui.structure.css
📄 Upload: assets/css/jquery-ui.structure.min.css
📄 Upload: assets/css/jquery-ui.theme.css
📄 Upload: assets/css/jquery-ui.theme.min.css
📄 Upload: assets/css/powerSlide-theme.css
📄 Upload: assets/css/powerSlide.css
📄 Upload: assets/fonts/fontawesome-webfont.eot
📄 Upload: assets/fonts/fontawesome-webfont.svg
📄 Upload: assets/fonts/fontawesome-webfont.ttf
📄 Upload: assets/fonts/fontawesome-webfont.woff
📄 Upload: assets/fonts/FontAwesome.otf
📄 Upload: assets/fonts/glyphicons-halflings-regular.eot
📄 Upload: assets/fonts/glyphicons-halflings-regular.svg
📄 Upload: assets/fonts/glyphicons-halflings-regular.ttf
📄 Upload: assets/fonts/glyphicons-halflings-regular.woff
📄 Upload: assets/fonts/glyphicons-halflings-regular.woff2
📄 Upload: assets/icons/android-chrome-192x192.png
📄 Upload: assets/icons/android-chrome-512x512.png
📄 Upload: assets/icons/apple-touch-icon.png
📄 Upload: assets/icons/favicon-16x16.png
📄 Upload: assets/icons/favicon-32x32.png
📄 Upload: assets/icons/favicon.ico
📄 Upload: assets/icons/site.webmanifest
📄 Upload: assets/images/img1.jpg
📄 Upload: assets/images/img2.jpg
📄 Upload: assets/images/img3.jpg
📄 Upload: assets/js/bootstrap.js
📄 Upload: assets/js/bootstrap.min.js
📄 Upload: assets/js/jquery-ui.js
📄 Upload: assets/js/jquery-ui.min.js
📄 Upload: assets/js/jquery.js
📄 Upload: assets/js/jquery.min.js
📄 Upload: assets/js/jquery.min.map
📄 Upload: assets/js/powerSlide.js
📄 Upload: custom.log
📄 Upload: error.log
📄 Upload: index.php
📄 Upload: init.php
📄 Upload: LICENSE
📄 Upload: README.md
----------------------------------------------------------------
Making changes to 56 files/folders to sync server state
Uploading: 3.59 MB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
creating folder "assets/"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: Client is closed because read ECONNRESET (data socket)
    at /home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5197:29
    at new Promise (<anonymous>)
    at FTPContext.handle (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:5179:16)
    at Client.sendIgnoringError (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:4226:25)
    at Client._openDir (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:4744:20)
    at Client.ensureDir (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:4735:24)
    at /home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:3555:126
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:3540:71
    at new Promise (<anonymous>)
Closing reason: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  code: 'ECONNRESET'
}
Error: Error: Client is closed because read ECONNRESET (data socket)
```

**Comment by FiniteLooper** [comment]
I am having the same issue.  I even went into my FTP manually and cleared out all files and tried deploying again. Same result.  This used to work, I'm not sure what happened.

**Comment by ao-tang** [comment]
Absolutely same issue!
Are you the first time to deploy it in server?Maybe because it spend too many time.
My solution is to use the FTP-Deploy (another tool in author's repo) in my computer at the first time（be careful to keep the local website file same to the remote repo) ,and next deploy can use the ftp-deploy-action.English is not my mother tongue,sorry for my mistake.

**Comment by shahriarshamit** [comment]
Thank I will try that.

**Comment by LBeukennoot** [comment]
Another solution is to add an empty file called '.ftp-deploy-sync-state.json' to the root folder you try to publish to

**Comment by shakib-gain** [comment]
facing the exact same issue

**Comment by FiniteLooper** [comment]
Does anyone know of a good alternative to this?  Is there another FTP deployment action that actually works reliably?

**Comment by VadymPatuk** [comment]
> Another solution is to add an empty file called '.ftp-deploy-sync-state.json' to the root folder you try to publish to

Works for me. Thanks 👍🏻

**Comment by im-alfa** [comment]
> Another solution is to add an empty file called '.ftp-deploy-sync-state.json' to the root folder you try to publish to

worked! thank you

**Comment by nombanafi** [comment]
> Another solution is to add an empty file called '.ftp-deploy-sync-state.json' to the root folder you try to publish to

Thanks!!!

**Comment by spylight-zz** [comment]
> Another solution is to add an empty file called '.ftp-deploy-sync-state.json' to the root folder you try to publish to

Thanks a lot...
