### ISSUE TITLE
Error: Timeout when trying to open data connection to <IP>:40192

### ISSUE THREAD

**Issue by masterminduday** [SamKirkland/FTP-Deploy-Action#409]
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
----------------------------------------------------------------
No file exists on the server "./public_html/.ftp-deploy-sync-state.json" - this must be your first publish! 🎉
The first publish will take a while... but once the initial sync is done only differences are published!
If you get this message and its NOT your first publish, something is wrong.
----------------------------------------------------------------
Local Files:	237
Server Files:	0
----------------------------------------------------------------
Calculating differences between client & server
----------------------------------------------------------------
📁 Create: assets
📁 Create: assets/data
📁 Create: assets/images
📁 Create: assets/img
📁 Create: assets/img/markers
📁 Create: assets/leaflet-countries
📁 Create: assets/map
📁 Create: assets/skins
📁 Create: assets/skins/lightgray
📁 Create: assets/skins/lightgray/fonts
📁 Create: assets/skins/lightgray/img
📄 Upload: 137.a401118c9fe18104e130.js
📄 Upload: 143.9a0fe862afe79f882f86.js
📄 Upload: 261.88a6a3ab621bd5c7fd58.js
📄 Upload: [33](https://github.com/masterminduday/RSSB-Web-Portal/actions/runs/5633217198/job/15261871561#step:6:34)9.15c9b9a88e77fc0badd8.js
📄 Upload: 3rdpartylicenses.txt
📄 Upload: 419.8c1b87123b6fd0bac00d.js
📄 Upload: 509.bd1eccf2ddfbddd4a810.js
📄 Upload: 550.eb62173ac1132fc26a70.js
📄 Upload: 578.1377c8567dca2fa06086.js
📄 Upload: 726.124a7018c83a2bd4031c.js
📄 Upload: Roboto-Thin.7431e6b3a27fc6c00b38.svg
📄 Upload: Roboto-Thin.9b3e35eb0a402cc52306.woff
📄 Upload: Roboto-Thin.e11b2308d1ace9c25083.woff2
📄 Upload: Roboto-Thin.faa946ed79baef82c81a.eot
📄 Upload: Roboto-ThinItalic.116dec4ea62225ecc9b1.ttf
📄 Upload: Roboto-ThinItalic.271f60b07567ee405bb4.woff2
📄 Upload: Roboto-ThinItalic.386a03e3cce1e95360c2.svg
📄 Upload: Roboto-ThinItalic.b9978de810b208c18a1a.eot
📄 Upload: Roboto-ThinItalic.be84e94690a6a2d14048.woff
📄 Upload: runtime.952c3a6a9e363d86176f.js
📄 Upload: scripts.[34](https://github.com/masterminduday/RSSB-Web-Portal/actions/runs/5633217198/job/15261871561#step:6:35)5179a7913dc9a[35](https://github.com/masterminduday/RSSB-Web-Portal/actions/runs/5633217198/job/15261871561#step:6:36)f8e.js
📄 Upload: socicon.578ecee55f406ce82f5b.ttf
📄 Upload: socicon.d1edd88f5dd84572d00d.svg
📄 Upload: socicon.ec23f2c6ea40d7043ca8.eot
📄 Upload: socicon.fa1cafd691508aa474d6.woff
📄 Upload: styles.10798445b583a46200b4.css
----------------------------------------------------------------
Making changes to 2[37](https://github.com/masterminduday/RSSB-Web-Portal/actions/runs/5633217198/job/15261871561#step:6:38) files/folders to sync server state
Uploading: 27.6 MB -- Deleting: 0 B -- Replacing: 0 B
----------------------------------------------------------------
creating folder "assets/"
creating folder "assets/data/"
creating folder "assets/images/"
creating folder "assets/img/"
creating folder "assets/img/markers/"
creating folder "assets/leaflet-countries/"
creating folder "assets/map/"
creating folder "assets/skins/"
creating folder "assets/skins/lightgray/"
creating folder "assets/skins/lightgray/fonts/"
creating folder "assets/skins/lightgray/img/"
uploading "137.a[40](https://github.com/masterminduday/RSSB-Web-Portal/actions/runs/5633217198/job/15261871561#step:6:41)1118c9fe18104e130.js"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: None of the available transfer strategies work. Last error response was 'Error: Timeout when trying to open data connection to <IP>:40192'.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:4802:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client._uploadFromStream (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:[44](https://github.com/masterminduday/RSSB-Web-Portal/actions/runs/5633217198/job/15261871561#step:6:45)90:13)
    at async Client._uploadLocalFile (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.4/dist/index.js:4[47](https://github.com/masterminduday/RSSB-Web-Portal/actions/runs/5633217198/job/15261871561#step:6:48)6:20)
Error: Error: None of the available transfer strategies work. Last error response was 'Error: Timeout when trying to open data connection to <IP>:40192'.

**Comment by SambasBoyyyy** [comment]
Facing the same issue.

**Comment by sarkaramitabh300** [comment]
Facing the same issue

**Comment by Sharifur** [comment]
facing same issue

**Comment by faizakbar18** [comment]
if you have cloud firewall or using cloud service like gcp or aws, you must allow `passive port range`

check on your ftp settings, for example like this
```
# Port range for passive connections replies. - for firewalling.
PassivePortRange          39000 40000
```

**Comment by edikurniawan-dev** [comment]
Try this [https://github.com/SamKirkland/FTP-Deploy-Action/issues/106#issuecomment-2186059117](https://github.com/SamKirkland/FTP-Deploy-Action/issues/106#issuecomment-2186059117)

**Comment by lucasffgomes** [comment]
Warning: Unexpected input(s) 'delete', valid inputs are ['server', 'username', 'password', 'port', 'protocol', 'local-dir', 'server-dir', 'state-name', 'dry-run', 'dangerous-clean-slate', 'exclude', 'log-level', 'security', 'timeout']
Run SamKirkland/FTP-Deploy-Action@v4.3.5
----------------------------------------------------------------
🚀 Thanks for using ftp-deploy. Let's deploy some stuff!   
----------------------------------------------------------------
If you found this project helpful, please support it
by giving it a ⭐ on Github --> https://github.com/SamKirkland/FTP-Deploy-Action
or add a badge 🏷️ to your projects readme --> https://github.com/SamKirkland/FTP-Deploy-Action#badge
Using the following excludes filters: ["**/node_modules/**","**/vendor/**","**/tests/**","**/storage/**"]
Creating local state at ./.ftp-deploy-sync-state.json
Local state created
Connected to 167.88.3[2](https://github.com/lucasffgomes/webdoc/actions/runs/10924270743/job/30323047314#step:8:2).101:22 (No encryption)
< SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u3
> QUIT
Failed to connect, are you sure your server works via FTP or FTPS? Users sometimes get this error when the server only supports SFTP.
----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------
----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------
Error: Timeout (control socket)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:5299:33)
    at Object.onceWrapper (node:events:633:[28](https://github.com/lucasffgomes/webdoc/actions/runs/10924270743/job/30323047314#step:8:29))
    at Socket.emit (node:events:519:28)
    at Socket._onTimeout (node:net:590:8)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Error: Error: Timeout (control socket)
