### ISSUE TITLE
Error: None of the available transfer modes work.

### ISSUE THREAD

**Issue by theJohnCode** [SamKirkland/FTP-Deploy-Action#416]
creating folder "vendor/webmozart/assert/src/"
uploading "app/Console/Kernel.php"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

Error: None of the available transfer modes work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:4803:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client._uploadFromStream (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:4491:13)
    at async Client._uploadLocalFile (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:4477:20)
Error: Error: None of the available transfer modes work.

I have this error uploading files to cpanel
It was working before, now its not working again

**Comment by melquesedek** [comment]
Same error here. Also using cPanel.
I did a test. I cleared all the directory and started sync from zero.
FTP-Deploy-Action was able to recreate the folder structure, but on file update, it failed, the same error as @theJohnCode reported above.

**Comment by Sharifur** [comment]
facing same issue

**Comment by Kenji2005** [comment]
same issue

**Comment by Ebubeuzor** [comment]
Please did you fix this?

**Comment by rersheed** [comment]
same issue here
