### ISSUE TITLE
Error: None of the available transfer strategies work.

### ISSUE THREAD

**Issue by sosmongare** [SamKirkland/FTP-Deploy-Action#421]
I am getting this error: Error: None of the available transfer strategies work. and it happens when it begins to uploading ".editorconfig"
Kindly assist.
![image](https://github.com/SamKirkland/FTP-Deploy-Action/assets/17259543/14072189-9820-4706-b8fc-d843c10ec20a)

**Comment by Khurram554** [comment]
same issue i got 

uploading ".editorconfig"
Error: None of the available transfer strategies work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3308:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client._uploadFromStream (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:2997:13)
    at async Client._uploadLocalFile (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:2983:20)
Error: None of the available transfer strategies work.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:3308:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client._uploadFromStream (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:2997:13)
    at async Client._uploadLocalFile (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.0.0/dist/index.js:2983:20)
