### ISSUE TITLE
Problem with deleting folder

### ISSUE THREAD

**Issue by AndrzejW2016** [SamKirkland/FTP-Deploy-Action#453]
Problem with deleting the folder via FTP, maybe it's the "/" character at the end of the path, or at the end of the path because the logs are imprecise "Core/Business/CMS/".

removing "Core/Business/CMS/index.php"
removing folder "Core/Business/CMS/"

----------------------------------------------------------------
--------------  🔥🔥🔥 an error occurred  🔥🔥🔥  --------------
----------------------------------------------------------------

----------------------------------------------------------------
----------------------  full error below  ----------------------
----------------------------------------------------------------

FTPError: 550 Can't remove directory: No such file or directory
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3945:39)
    at Socket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.1.0/dist/index.js:3786:44)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 550
}
Error: FTPError: 550 Can't remove directory: No such file or directory

**Comment by gmakwa22** [comment]
This is how I fixed it - Turns out I had something in my gitignore file that was creating the conflict - Delete the files on your server and the gitignore data then push again. I must have accidently added something to the gitignore file this was happening on a few of my sites but its fixed now.
