### ISSUE TITLE
Issue while using ftps with port 21 and small file sizes

### ISSUE THREAD

**Issue by koolkabin** [SamKirkland/FTP-Deploy-Action#466]
**Bug Description**
while making ftp file deploy to a server using ftps over port 21, its not working and throwing following error

FTPError: 451-Error during read from data connection
451-16 Kbytes used (0%) - authorized: 512000 Kb
451-Transfer aborted
451 0.184 seconds (measured here), 86.75 Kbytes per second
    at FTPContext._onControlSocketData (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5254:39)
    at TLSSocket.<anonymous> (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/4.3.3/dist/index.js:5095:44)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 451
}

**Comment by MadalitsoNyemba** [comment]
Try to change the version and use `uses: SamKirkland/FTP-Deploy-Action@v4.3.5`

**Comment by koolkabin** [comment]
yeah i got that and it help me fix that... 

thanks
