### ISSUE TITLE
not deploying in subfolder

### ISSUE THREAD

**Issue by sherz12r** [SamKirkland/FTP-Deploy-Action#469]
name: Deploy Project on push
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - name: d
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.SERVER_PASS }}
          server-dir: ${{ secrets.SERVER_PATH }}/
          
          
         i tried follwowing in server_path
         tried follwoing

/public_html/projectfolder => no project found 
/projectfolder is creating folder in root outside public_html
public_html/projectfolder => no project found 
public_html/ => no project found 
my project is in subfolder like public_html/projectfolder 
i want to deploy in projectfolder any help?

**Comment by sherz12r** [comment]
thanks for replying updated then i have follwoing
Error: None of the available transfer strategies work. Last error response was 'Error: Timeout when trying to open data connection to ***:60185'.
    at Client.prepareTransfer (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:4811:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client._uploadFromStream (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:4496:13)
    at async Client._uploadLocalFile (/home/runner/work/_actions/SamKirkland/FTP-Deploy-Action/v4.3.5/dist/index.js:4482:20)
Error: Error: None of the available transfer strategies work. Last error response was 'Error: Timeout when trying to open data connection to ***:601

**Comment by Trainax** [comment]
Try checking if your server needs a special port for FTP. From your original comment I assume you are using FTP on port 21 (default values), maybe your host uses a different port for FTP or only accepts FTPS connections (which need to be set in the action YML file)

**Comment by sherz12r** [comment]
i saw this is updating files but not complete please see image it giving error after uploading many folders
![gitCapture](https://github.com/SamKirkland/FTP-Deploy-Action/assets/46225971/eb782428-03b4-43bb-a07a-a219d945429c)

**Comment by espenjohannessen** [comment]
I'm having the same issue! Any ideas how to solve this? FTP transfers works fine through other FTP clients, but I'm getting the same errer as above when running the GitHub action!

**Comment by espenjohannessen** [comment]
Just as I posted this I realized that the issue was related to passive FTP mode and adding the passive ports (49152-65534) to the server firewall solved the issue!

**Comment by RayhanulSumon** [comment]
Does anyone get a solution?

**Comment by Oscar-T24** [comment]
I get the same error. Perhaps `FTP-Deploy-Action ` assumes your server is running in passive mode ? This is obviously not the case on my server and I don't understand why Github action is using "high" ports like 601 while I expect a specific port. Additionaly my router has not forwarded these ports to my server hence why I get timeouts.

Any help will be greatly appreciated.

**Comment by kompasstech** [comment]
Check your Firewall, Creating Problems in Almalinux. Same Time-out error. Once disable the Firewall it Works

**Comment by mhimon** [comment]
Facing same issue!

**Comment by arbazKnarkz** [comment]
facing same issue
