### ISSUE TITLE
Action do not fail even if secret is not defined

### ISSUE THREAD

**Issue by LeoSeyers** [SamKirkland/FTP-Deploy-Action#60]
**Bug Description**
It's the first time I use Git Actions, I was previously using git-ftp in my pipelines on Bitbucket.
I assumed my first action push was going to fail because the ftp password secrets was not defined yet. However the action returned the success status, while the error is there and the action clearly failed (willingly).

**My Action Config**
I haven't changed  the initial config example (except for the credentials).

**My Action Log**
```
(node:1) UnhandledPromiseRejectionWarning: Error: Input required and not supplied: ftp-password
    at Object.getInput (/deploy.js:860:15)
    at getUserArguments (/deploy.js:683:28)
    at /deploy.js:667:31
    at Generator.next (<anonymous>)
    at /deploy.js:652:71
    at new Promise (<anonymous>)
    at module.exports.131.__awaiter (/deploy.js:648:12)
    at run (/deploy.js:666:12)
    at Object.131 (/deploy.js:678:1)
    at __webpack_require__ (/deploy.js:22:30)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SamKirkland** [comment]
Thanks for finding this!
Fixed!
